import type {ResourceManifest, ResourceMatrixRow} from './types';

export const EXAMPLE_RESOURCE_MATRIX: ResourceMatrixRow[] = [
  {
    platform: 'windows',
    arch: 'x64',
    supportedModes: ['core', 'full', 'online-bootstrap', 'importable'],
    defaultBundleId: 'openclaw-windows-x64-full',
    notes: ['Windows x64 keeps WSL-based runtime assets isolated to Windows adapter only.'],
  },
  {
    platform: 'windows',
    arch: 'arm64',
    supportedModes: ['core', 'online-bootstrap', 'importable'],
    defaultBundleId: 'openclaw-windows-arm64-core',
    notes: ['ARM64 skips the current full runtime preset until Windows-specific runtime assets are ready.'],
  },
  {
    platform: 'macos',
    arch: 'x64',
    supportedModes: ['core', 'full', 'online-bootstrap', 'importable'],
    defaultBundleId: 'openclaw-macos-x64-full',
    notes: ['Intel macOS can run native launcher/node assets without borrowing Windows logic.'],
  },
  {
    platform: 'macos',
    arch: 'arm64',
    supportedModes: ['core', 'full', 'online-bootstrap', 'importable'],
    defaultBundleId: 'openclaw-macos-arm64-full',
    notes: ['Apple Silicon prefers arm64-native bundles; Rosetta remains an environment fact, not a fake cross-platform runtime.'],
  },
];

export const EXAMPLE_RESOURCE_MANIFEST: ResourceManifest = {
  schemaVersion: '1.0.0',
  productVersion: '0.2.0',
  generatedAt: '2026-03-18T00:00:00.000Z',
  compatibilityRange: {
    minLauncherVersion: '0.1.0',
    supportedPlatforms: ['windows', 'macos'],
    supportedArchitectures: ['x64', 'arm64'],
  },
  defaultSourcePriority: ['local-import', 'lan', 'mirror-cn', 'official', 'custom'],
  bundles: [
    {
      id: 'openclaw-windows-x64-full',
      name: 'OpenClaw Windows x64 Full',
      version: '0.2.0',
      platform: 'windows',
      arch: 'x64',
      mode: 'full',
      resourceIds: ['launcher-win-x64', 'node-win-x64', 'rootfs-win-x64', 'gateway-win-x64', 'checksum-win-x64'],
      description: 'Windows x64 full preset with launcher, Node, rootfs, gateway bundle and checksums.',
    },
    {
      id: 'openclaw-macos-arm64-full',
      name: 'OpenClaw macOS arm64 Full',
      version: '0.2.0',
      platform: 'macos',
      arch: 'arm64',
      mode: 'full',
      resourceIds: ['launcher-macos-arm64', 'node-macos-arm64', 'runtime-macos-arm64', 'gateway-macos-arm64', 'checksum-macos-arm64'],
      description: 'macOS Apple Silicon full preset using native runtime assets.',
    },
  ],
  resources: [
    {
      id: 'launcher-win-x64',
      name: 'OpenClaw Launcher (Windows x64)',
      version: '0.2.0',
      platform: 'windows',
      arch: 'x64',
      resourceType: 'launcher',
      modeTags: ['core', 'full'],
      size: 42_000_000,
      sha256: 'example-launcher-win-x64-sha256',
      filename: 'openclaw-launcher-win-x64.zip',
      relativePath: 'windows/x64/launcher/openclaw-launcher-win-x64.zip',
      sources: [
        {type: 'official', url: 'https://downloads.openclaw.example/windows/x64/launcher.zip', priority: 40},
        {type: 'mirror-cn', url: 'https://mirror-cn.openclaw.example/windows/x64/launcher.zip', priority: 20},
      ],
      installHints: {extractDir: 'launcher', executablePath: 'OpenClaw Launcher.exe'},
      dependencies: [],
      optional: false,
      description: 'Desktop launcher package for Windows x64.',
    },
    {
      id: 'node-win-x64',
      name: 'Node.js Runtime (Windows x64)',
      version: '22.14.0',
      platform: 'windows',
      arch: 'x64',
      resourceType: 'node',
      modeTags: ['core', 'full', 'online-bootstrap', 'importable'],
      size: 35_000_000,
      sha256: 'example-node-win-x64-sha256',
      filename: 'node-v22.14.0-win-x64.zip',
      relativePath: 'windows/x64/node/node-v22.14.0-win-x64.zip',
      sources: [
        {type: 'official', url: 'https://nodejs.org/dist/v22.14.0/node-v22.14.0-win-x64.zip', priority: 50},
        {type: 'local-import', path: './imports/node-v22.14.0-win-x64.zip', priority: 10},
      ],
      installHints: {extractDir: 'node', executablePath: 'node.exe', repairStrategy: 'redownload'},
      dependencies: [],
      optional: false,
      description: 'Pinned Node.js package for Windows x64.',
    },
    {
      id: 'rootfs-win-x64',
      name: 'OpenClaw RootFS (Windows x64)',
      version: '2026.03.18',
      platform: 'windows',
      arch: 'x64',
      resourceType: 'rootfs',
      modeTags: ['full', 'importable'],
      size: 580_000_000,
      sha256: 'example-rootfs-win-x64-sha256',
      filename: 'openclaw-rootfs-win-x64.tar.zst',
      relativePath: 'windows/x64/rootfs/openclaw-rootfs-win-x64.tar.zst',
      sources: [
        {type: 'official', url: 'https://downloads.openclaw.example/windows/x64/rootfs.tar.zst', priority: 50},
        {type: 'lan', url: 'http://192.168.1.20:8080/openclaw/windows/x64/rootfs.tar.zst', priority: 15},
      ],
      installHints: {repairStrategy: 'reimport', postInstallNotes: ['Used only by Windows adapter import flow.']},
      dependencies: [{resourceId: 'checksum-win-x64', reason: 'Must validate rootfs before import.'}],
      optional: false,
      description: 'Windows-specific runtime rootfs archive. Not shared with macOS.',
    },
    {
      id: 'gateway-win-x64',
      name: 'Gateway Bundle (Windows x64)',
      version: '0.2.0',
      platform: 'windows',
      arch: 'x64',
      resourceType: 'gateway-bundle',
      modeTags: ['core', 'full', 'online-bootstrap'],
      size: 60_000_000,
      sha256: 'example-gateway-win-x64-sha256',
      filename: 'openclaw-gateway-win-x64.zip',
      relativePath: 'windows/x64/gateway/openclaw-gateway-win-x64.zip',
      sources: [{type: 'official', url: 'https://downloads.openclaw.example/windows/x64/gateway.zip', priority: 50}],
      installHints: {extractDir: 'gateway', executablePath: 'gateway/server.js'},
      dependencies: [{resourceId: 'node-win-x64', reason: 'Gateway bundle requires managed Node runtime.'}],
      optional: false,
      description: 'Gateway package for Windows x64.',
    },
    {
      id: 'checksum-win-x64',
      name: 'Checksums (Windows x64)',
      version: '2026.03.18',
      platform: 'windows',
      arch: 'x64',
      resourceType: 'checksum',
      modeTags: ['full', 'importable'],
      size: 12_000,
      sha256: 'example-checksum-win-x64-sha256',
      filename: 'SHA256SUMS.txt',
      relativePath: 'windows/x64/manifest/SHA256SUMS.txt',
      sources: [{type: 'official', url: 'https://downloads.openclaw.example/windows/x64/SHA256SUMS.txt', priority: 50}],
      installHints: {checksumFile: 'SHA256SUMS.txt'},
      dependencies: [],
      optional: false,
      description: 'Checksum manifest for Windows x64 runtime assets.',
    },
    {
      id: 'launcher-macos-arm64',
      name: 'OpenClaw Launcher (macOS arm64)',
      version: '0.2.0',
      platform: 'macos',
      arch: 'arm64',
      resourceType: 'launcher',
      modeTags: ['core', 'full'],
      size: 44_000_000,
      sha256: 'example-launcher-macos-arm64-sha256',
      filename: 'openclaw-launcher-macos-arm64.dmg',
      relativePath: 'macos/arm64/launcher/openclaw-launcher-macos-arm64.dmg',
      sources: [{type: 'official', url: 'https://downloads.openclaw.example/macos/arm64/launcher.dmg', priority: 50}],
      installHints: {postInstallNotes: ['Mount DMG and copy the app bundle into Applications.']},
      dependencies: [],
      optional: false,
      description: 'Desktop launcher image for Apple Silicon.',
    },
    {
      id: 'node-macos-arm64',
      name: 'Node.js Runtime (macOS arm64)',
      version: '22.14.0',
      platform: 'macos',
      arch: 'arm64',
      resourceType: 'node',
      modeTags: ['core', 'full', 'online-bootstrap', 'importable'],
      size: 32_000_000,
      sha256: 'example-node-macos-arm64-sha256',
      filename: 'node-v22.14.0-darwin-arm64.tar.gz',
      relativePath: 'macos/arm64/node/node-v22.14.0-darwin-arm64.tar.gz',
      sources: [{type: 'official', url: 'https://nodejs.org/dist/v22.14.0/node-v22.14.0-darwin-arm64.tar.gz', priority: 50}],
      installHints: {extractDir: 'node', executablePath: 'bin/node'},
      dependencies: [],
      optional: false,
      description: 'Pinned Node.js package for macOS arm64.',
    },
    {
      id: 'runtime-macos-arm64',
      name: 'OpenClaw Runtime (macOS arm64)',
      version: '0.2.0',
      platform: 'macos',
      arch: 'arm64',
      resourceType: 'runtime',
      modeTags: ['full', 'importable'],
      size: 410_000_000,
      sha256: 'example-runtime-macos-arm64-sha256',
      filename: 'openclaw-runtime-macos-arm64.tar.gz',
      relativePath: 'macos/arm64/runtime/openclaw-runtime-macos-arm64.tar.gz',
      sources: [{type: 'official', url: 'https://downloads.openclaw.example/macos/arm64/runtime.tar.gz', priority: 50}],
      installHints: {extractDir: 'runtime', repairStrategy: 'redownload'},
      dependencies: [{resourceId: 'checksum-macos-arm64', reason: 'Runtime must pass checksum verification.'}],
      optional: false,
      description: 'Native macOS runtime bundle for Apple Silicon.',
    },
    {
      id: 'gateway-macos-arm64',
      name: 'Gateway Bundle (macOS arm64)',
      version: '0.2.0',
      platform: 'macos',
      arch: 'arm64',
      resourceType: 'gateway-bundle',
      modeTags: ['core', 'full', 'online-bootstrap'],
      size: 58_000_000,
      sha256: 'example-gateway-macos-arm64-sha256',
      filename: 'openclaw-gateway-macos-arm64.tar.gz',
      relativePath: 'macos/arm64/gateway/openclaw-gateway-macos-arm64.tar.gz',
      sources: [{type: 'official', url: 'https://downloads.openclaw.example/macos/arm64/gateway.tar.gz', priority: 50}],
      installHints: {extractDir: 'gateway', executablePath: 'gateway/server.js'},
      dependencies: [{resourceId: 'node-macos-arm64', reason: 'Gateway bundle requires managed Node runtime.'}],
      optional: false,
      description: 'Gateway package for macOS arm64.',
    },
    {
      id: 'checksum-macos-arm64',
      name: 'Checksums (macOS arm64)',
      version: '2026.03.18',
      platform: 'macos',
      arch: 'arm64',
      resourceType: 'checksum',
      modeTags: ['full', 'importable'],
      size: 12_000,
      sha256: 'example-checksum-macos-arm64-sha256',
      filename: 'SHA256SUMS.txt',
      relativePath: 'macos/arm64/manifest/SHA256SUMS.txt',
      sources: [{type: 'official', url: 'https://downloads.openclaw.example/macos/arm64/SHA256SUMS.txt', priority: 50}],
      installHints: {checksumFile: 'SHA256SUMS.txt'},
      dependencies: [],
      optional: false,
      description: 'Checksum manifest for macOS arm64 runtime assets.',
    },
  ],
};
